### ISSUE TITLE
Hide projectiles in the same way as corpses?

### ISSUE THREAD

**Issue by LangLangBart** [nanihadesuka/autociv#12]
Can you hide the projectiles the same way you hide the corpses?

In the boonGUI mod the objects are much bigger and it looks funny when there are many objects on the ground. :sweat:

<img src="https://raw.githubusercontent.com/LangLangBart/ImagePool/c40d61b506a49762e24376ed27bbccd35effd894/storage/10_Oct_22_at_23_51_59_autociv_options.jpg" width="600">

<img src="https://raw.githubusercontent.com/LangLangBart/ImagePool/f59b6751f8a866a5574ec73c4c918739c55713d5/storage/10_Oct_22_at_23_53_54_projectile-blasted.png" width="600">

**Comment by nanihadesuka** [comment]
A projectile is not an corpse entity (I think is not even an entity). With current autociv settings is not possible. Also is not possible  to do it as a mod, you need to change engine C++ code, is kind of hardcoded so would need work. Best to ask Wraitii  or Freagarach
