### ISSUE TITLE
pingall update

### ISSUE THREAD

**Issue by Kampot-0ad** [nanihadesuka/autociv#13]
Please extend: ChatCommandHandler~autociv.js

const ignore = new Set([selfNick, "Ratings", "WFGBot", "Triumvir", "user1", "Dunedan", "Rollo"]);
to:
const ignore = new Set([selfNick, "Ratings", "WFGBot", "WFGbot", "Triumvir", "user1", "Dunedan", "Rollo", "stanleysweet","vladislavbelov","Stan`","~Defc0n"]);

To avoid pinging devs, they never play. WFGBot and WFGbot (both same 0.25 and 0.26 - probably made this way to be able run then at the same time)

**Comment by nanihadesuka** [comment]
Added in 69ba2fe9317e40cdcc9c9ba463cfc8ea2d1ed9d0
New release 26.1.0 is already live and ready to download :)
