### ISSUE TITLE
Space Hotkey unintentional jumps

### ISSUE THREAD

**Issue by IlanFrumer** [nanihadesuka/autociv#3]
`Space`  is already assigned by default to  hotkey to "Focus on last attack notification"
Thus, every time I try to build a building with space hotkeys the focus  jumps unintentionaly before I'm able to place the building.

![image](https://user-images.githubusercontent.com/3116399/133205750-649fe370-d1f8-472e-90ba-6cc1c03f95b0.png)

**Comment by nanihadesuka** [comment]
Autociv shows a popup suggestion to change it when you first install . see a5762c4aafed849fa890a24b8ed9c47669a799d0
The solution is to change it to something else ... duh 😄 
Not that I can't really change 60+ hotkeys now anway.
Set as solved
