### ISSUE TITLE
fix the loosing chat context when changing chat context via hotkey

### ISSUE THREAD

**Issue by sl5net** [nanihadesuka/autociv#30]
maybe this helps:

it saves last chat context temporarily and put it in again when you press tab in empty chat

https://github.com/sl5net/autocivP/commit/6898718ba17873a23dfc4b7c8f76e6da29715c54#diff-4099c0fac2a670d13d58bc429db0229c58663774b0d705cdc1bde16ef8842a41R127

**Comment by nanihadesuka** [comment]
Read the commit. I see alot of unrelated random code changes. Can you post the part for the issue only please?

**Comment by sl5net** [comment]
https://github.com/sl5net/autocivP/commit/6898718ba17873a23dfc4b7c8f76e6da29715c54#diff-009c86d9a9db6227c68f295cb6a6ddd68be94d838ea0064aec068ee9c0f8be90R119
```js
		if(chatInput?.caption && chatInput.caption.length > 0){
				selfMessage(`getting your chat "${chatInput.caption}" by press ⟦Tab⟧ later`);
				g_backupMessageBeforeChangeContContextViaHotkey = chatInput.caption
			// this fixes the problem with changing chat context via hotkey a bit. it saves last chat context temporarily and but it in again when you press tab 23-0724_1543-57
			}

			return that.openPage(g_IsObserver ? "/observers" : "/chat"); // works
		});
```

then later

https://github.com/sl5net/autocivP/commit/6898718ba17873a23dfc4b7c8f76e6da29715c54#diff-4099c0fac2a670d13d58bc429db0229c58663774b0d705cdc1bde16ef8842a41R127
```js
  if (!caption.length){ // trigers when no caption content is in
    // selfMessage(`116: ${caption} = ${caption}`)
    // selfMessage(`116: ${caption} = ${caption}`)


    if(  g_backupMessageBeforeChangeContContextViaHotkey ) // this fixes the problem with changing chat context via hotkey a bit. it saves last chat context temporarily and but it in again when you press tab 23-0724_1543-57
    {
      // selfMessage(`102: g_backupMessageBeforeChangeContContextViaHotkey = ${g_backupMessageBeforeChangeContContextViaHotkey}`)
      guiObject.caption = g_backupMessageBeforeChangeContContextViaHotkey
      guiObject.buffer_position = g_backupMessageBeforeChangeContContextViaHotkey.length;
      g_backupMessageBeforeChangeContContextViaHotkey = ''
      return
    }
```

**Comment by nanihadesuka** [comment]
Ok, I gave it a though. Won't add for following reasons:
* This feature can be replicated by just copy + paste. Something any user is already familiar with and works always.
* The way the feature is triggered (using tab) is in conflict with the expected default behaviour (autocomplete). Not a great used  experience.
* This feature is for example used in command lines using arrow up arrow down. Those events are not implemented for input type object in pyrogenesis, so we can't add it.

Overall the idea is good but is not something I think this mod needs.
