### ISSUE TITLE
F4 doesn't open AutoCiv window.

### ISSUE THREAD

**Issue by urajsingh** [nanihadesuka/autociv#4]
F4 doesn't open anything but I can assure that everything is installed correctly.

Shift+F4 readme works but nothing happens when I press F4 please do help. :( Even tried changing to another key, it doesn't show up.

Latest 0ad. and latest Autociv from github.  No other mods except Delenda Est (disabled).

**Comment by nanihadesuka** [comment]
F4 doesn't do anything because it doesn't.  If I remember correctly I used F4 in the past to open the custom hotkey editor autociv had but when the official hotkey editor was added to the game I removed it.

**Comment by urajsingh** [comment]
Ohh. So basically, all the settings are baked in? 
Was a little confused as to how to use it. Didn't see any instructions for newcomers.

**Comment by nanihadesuka** [comment]
The hotkey editor is now baked in 0ad, the rest of the mod not. :)
