### ISSUE TITLE
Removal of "numberOfGatherer" bar

### ISSUE THREAD

**Issue by Souk21** [nanihadesuka/autociv#8]
Hello, first of all, thank you for this great mod !
I was wondering if there was a reason for the removal of the status bar that indicates how many workers are currently gathering a resources ?
(commit https://github.com/nanihadesuka/autociv/commit/56bd072cb021cbcca4af7006bc8475edcbe929aa )
I thought that it was because it was implemented in the vanilla game, but I wasn't able to find it in the settings.

Thanks again !

**Comment by nanihadesuka** [comment]
Hi Soku21! Reason: I removed it because it gave too much much unfair advantage and had some bugs hard to fix (and keep being compatible with vanilla). For this case, I think it would be better to ask to include this feature in the main game directly.
